version: '2'

services:
  ldap:
    image: moresandeep/knox-dev:master
    command: /ldap.sh

  avatica:
    image: joshelser/avatica-hsqldb:1.9.0
    ports:
      - "8765:8765"

  knox:
    image: joshelser/knox-gateway
    ports:
      - "8443:8443"
    volumes:
      - ./topologies:/knox-0.10.0/conf/topologies
      - ./avatica:/knox-0.10.0/data/services/avatica
    depends_on:
      - avatica
      - ldap
