version: '2'

services:
  ldap:
    image: moresandeep/knox-dev:master
    command: /ldap.sh

  avatica:
    image: joshelser/avatica-hsqldb:1.9.0
    ports:
      - "8765:8765"

  knox:
    image: joshelser/knox-gateway:0.10.0
    ports:
      - "8443:8443"
    volumes:
      - ./topologies:/knox/conf/topologies
      - ./avatica:/knox/data/services/avatica
      - ./keystores:/knox/data/security/keystores
      - ./master:/knox/data/security/master
    depends_on:
      - avatica
      - ldap
