version: '2'

services:
  knox-dev:
    build:
      context: ./build
      args:
        gitcommand: git clone https://github.com/apache/knox.git knox
        knoxversion: 0.11.0-SNAPSHOT
    image: moresandeep/knox-dev:master


  ldap:
    image: moresandeep/knox-dev:master
    command: /ldap.sh

  avatica:
    image: joshelser/avatica-hsqldb:1.9.0
    ports:
      - "8765:8765"

  knox:
    image: moresandeep/knox-dev:master
    ports:
      - "8443:8443"
    command: /gateway.sh
    volumes:
      - ./topologies:/knox-runtime/conf/topologies
      - ./avatica:/knox-runtime/data/services/avatica
    depends_on:
      - ldap
